# Generated by Django 6.1.1 on 2026-09-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(max_length=255)),
                ('package_title', models.CharField(blank=True, max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=50)),
                ('travel_date', models.CharField(blank=True, max_length=50)),
                ('return_date', models.CharField(blank=True, max_length=50)),
                ('travelers', models.IntegerField(default=1)),
                ('tier', models.CharField(blank=True, max_length=255)),
                ('price_per_person', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('booked_on', models.CharField(blank=True, max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=100)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('original_price', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(default=4.9)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('image', models.TextField()),
                ('overview', models.TextField()),
                ('includes', models.JSONField(blank=True, default=list)),
                ('group_size', models.CharField(blank=True, max_length=100)),
                ('departure', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=100, unique=True)),
                ('content', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('avatar', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('location', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
